name: Llibrary CI

on:
  push:
    branches:
      - main

jobs:
  library:
    uses: MrRamPoudel/shared-dotnet-library-pipeline/.github/workflows/parent-pipeline.yml@v1

    permissions:
      contents: write
      packages: write